### ISSUE TITLE
Error sending message in chat

### ISSUE THREAD

**Issue by marciotisouza** [olton/Pandora#2]
I'm testing Pandora and on the chat screen when I send a message the following error is appearing:

Uncaught TypeError: l.format is not a function
    at Object.add (metro.js:7765)
    at <anonymous>:36:18

**Comment by olton** [comment]
Thank you. Yes, need update metro4 to latest version. I will update metro4 in template after 3 jul. Now I am in the hospital.

**Comment by marciotisouza** [comment]
Thank you for your feedback, I appreciate your improvement.

**Comment by olton** [comment]
Fixed, thanks
