### ISSUE TITLE
abnormal behaviour in links

### ISSUE THREAD

**Issue by BillyTheCowBoy** [olton/Pandora#3]
Hi Olton,

i would like to redirect to https://localhost:32784/Survey/ListOfSurvey as showed in below photo.
![1](https://user-images.githubusercontent.com/61674878/78504278-a0879680-779e-11ea-8ae2-d70e5581da62.PNG)

But when i click in it . it redirect me to https://localhost:32784/Survey/index.html#Survey/ListOfSurvey

![2](https://user-images.githubusercontent.com/61674878/78504304-e6445f00-779e-11ea-9bf8-59385bce82ad.PNG)

here is my code .i just simple using Pandora template .
![3](https://user-images.githubusercontent.com/61674878/78504358-3d4a3400-779f-11ea-851a-24471046fdd6.PNG)

i have no idea why it is like this. do you have any idea about it ?

**Comment by olton** [comment]
change this code for your purpose https://github.com/olton/Pandora/blob/master/source/js/index.js#L71

**Comment by BillyTheCowBoy** [comment]
Hi Olton,

it solved my problem . 
Thank you so much.
